### ISSUE TITLE
documentation inconsistency

### ISSUE THREAD

**Issue by benjamin-kirkbride** [yaakovLowenstein/hx-requests#1]
Seems like the package name is `hx-requests`, but the docs say `simple-django-htmx`

![image](https://user-images.githubusercontent.com/3373830/234104010-8fc0c4c4-b8eb-4c9d-8ec0-9f03b770fea2.png)

**Comment by yaakovLowenstein** [comment]
Yes, that's correct.

I moved the project over from that repo (simple-django-htmx). I am in the process of deprecating that one.

I continued development on this repo and I am currently in middle of writing documentation for it. 

Probably should have updated the Readme first :).

Documentation is still in progress, but you can find it here: https://hx-requests.readthedocs.io/en/latest/index.html

**Comment by benjamin-kirkbride** [comment]
Thanks for the info :grinning:.

A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create awesome-python-htmx; a collection of active tools/libraries/projects in that space. Your project seems like an obvious thing to include.

In addition to that, if you could also participate in PyHAT-stack/awesome-python-htmx#1 that would be greatly appreciated!

**Comment by yaakovLowenstein** [comment]
@benjamin-kirkbride I checked out the repo and it looks very cool! 

What are you thinking in terms of 'participation'? 

Also I see that you have simple-django-htmx listed in the Readme, I would replace that with this repo because I continued development here.

**Comment by benjamin-kirkbride** [comment]
I linked to a specific discussion with some detail about what I'm hoping to do, but part of it is just giving feedback as you have :)

Like I mention in https://github.com/PyHAT-stack/awesome-python-htmx/discussions/1, I'm hoping to gather a quorum to help consolidate efforts around building out the tooling for great htmx+Python synergy.

I have updated the entry to `hx-requests`, let me know how that looks :)
