### ISSUE TITLE
Option to not process `get_context_data` on post request

### ISSUE THREAD

**Issue by eschnitzler** [yaakovLowenstein/hx-requests#100]
I'm currently making a long API call in the `get_context_data` method. I only need to make this call on GET requests and I noticed that POST requests are trying to make the same call and are becoming very slow. If it is unnecessary or unwanted, I propose a way to 'turn off' `get_context_data` on POST requests.

**Comment by yaakovLowenstein** [comment]
There is right now an attribute for `get_view_context`. if False it does not call get context data from the view

**Comment by eschnitzler** [comment]
The issue is the get_context_data from the hx_request. Is that also included?
