### ISSUE TITLE
Better way of handling context for modal body

### ISSUE THREAD

**Issue by yaakovLowenstein** [yaakovLowenstein/hx-requests#34]
Instead of adding the body to the context, use an include for the body and then there is no issue with putting context into the regular get_context_data function.

The issue previously was that because it was rendering the body separately, the context needed to be separate. But as an include it can all be one context.

One issue I am running into is that if the body is not a file path then it can't be included. There are multiple ways to go about this and I'm not sure which yet to do

### A template tag to render the body:
**Pros:** 
- No need for an extra template

**Cons:**
- Feels a little clunky for users of the package to need to use the template tag in their own modal template (even if is documented
- The template tag isn't super straightforward. It needs to do a render to string on the template using the context

### Create a new template for when body is a string
A new template  `modal_body` and when the body is just a string (or Html) render it in `modal_body` and set `self.body` on the HxRequest to `modal_body.html`
**Pros:**
- For users of the package all you need to do is use an include on the `self.body`

**Cons:**
- An extra template just for this feels unusual

**Comment by sgordon16** [comment]
Can you elaborate on the multiple ways in the last point?

**Comment by yaakovLowenstein** [comment]
> Can you elaborate on the multiple ways in the last point?

Added above
