### ISSUE TITLE
Should the context from the view be fetched in the mixin instead of the base HxRequest 🤔

### ISSUE THREAD

**Issue by yaakovLowenstein** [yaakovLowenstein/hx-requests#39]
The point would be to decouple HxRequests some what from the view. Currently because it calls the view's context data in the class itself it is 100% coupled to a view. Calling the context in the mixin and passing it to the HxRequest would decouple it because then even without a view an HxRequest would still work.

**Comment by sgordon16** [comment]
It will also break if the view does't have `get_context_data` defined.
