### ISSUE TITLE
hx_request setup always calls the views get method

### ISSUE THREAD

**Issue by sgordon16** [yaakovLowenstein/hx-requests#67]
This seems to have been done intentionally but I don't understand why. There is a comment there saying it's needed to "setup necessary parts for the context". I'm assuming  you meant that the `get` method in a `TemplateView` calls the `get_context_data` method. I'm not sure why that's needed if we are forwarding the response to the `HXRequest` and not using the view to handle the request.

This is also assuming that the view has a `get` method which may very well **not** be the case as I mentioned in issue #45
Another issue with this is that it forces you to call the view's get_context_data method if you're using a `TemplateView`. There are instances where one may specifically not want all of the views context to get pulled when it involves complex computations and db queries that are not needed for the hx response.

It seems like anyway we are pulling in the view's context in the `BaseHXRequest` `get_context_data`, which, again, is assuming that we are dealing with a `TemplateView` which may or may not be the case. It should first check if the view has a `get_context_data` method.

**Comment by yaakovLowenstein** [comment]
The get is needed to set things up. I.e. in an `UpdateView` view if you do not call get you will have the `object` and therefore it will error because it is expecting the object. `get` needs to be called to set up the parts of the view that are needed in the context. It is an idea to make a way to opt out of it if you do not need it.

**Comment by sgordon16** [comment]
It seems like that's the only case where an attribute is set one the view in the `get` method. In any case, why do you need the view's object to be set for an hx request? The `get_hx_object` get's the object from the request GET parameters and is not using the view's object. I think that was only necessary before this PR #48 was merged.

**Comment by yaakovLowenstein** [comment]
As long as the context is relying on something being setup by the view in the `get`, `get` needs to be called. Another exmaple:
![image](https://github.com/yaakovLowenstein/hx-requests/assets/50084761/8e4a0d1f-abf9-4d7c-a2df-1f09e8ad8b83)

**Comment by sgordon16** [comment]
I see what you mean. This does seem to defeat a lot of the purpose of async loading with htmx. Since by calling the view's `get` you are essentially rendering the entire page for every htmx request including all of the db queries for the page (since the response is actually rendered when the `get` method is called it must evaluate all the db queries). I'm not exactly sure what the solution is though. There needs to be way to pass on some of the context from the view and not all of it, though I don't know how that would be possible.

**Comment by sgordon16** [comment]
Calling the `get_context_data` method alone would not evaluate the db queries because are lazily evaluated so I think calling it in the `BaseHXRequest` is acceptable. I still think there should be a way to opt out of that maybe using a boolean attribute `use_view_context` or something. The real issue though is calling the `get` method because it needs to evaluate all the queries in order to return the rendered response.

**Comment by sgordon16** [comment]
This makes think that really the main advantage of HXRequests is that it has the original view context otherwise we could just use regular Django views.

**Comment by yaakovLowenstein** [comment]
Great point.
I am working on a way to call the `get` without returning the response.

In hxr-requests it will define the get for the django views that need it. hx-requests will also provide a way to define you own in settings if you have a custom model.
